version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports:
      - "4000:3000"
    environment:
      - PORT: 3000
    depends_on:
      - mongo

volumes:
  mongo-data: {}